apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contour
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: contour
    server: https://kubernetes.default.svc
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: contour
    targetRevision: {{ .Values.contour.targetRevision }}
    helm:
      releaseName: contour
      {{- with .Values.contour.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  syncPolicy:
    {{- toYaml .Values.contour.syncPolicy | nindent 4 }}