apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: external-dns
    targetRevision: {{ .Values.externalDns.targetRevision }}
    helm:
      releaseName: external-dns
      {{- with .Values.externalDns.values }}
      values: |
        {{- toYaml . | nindent 8 }}
      {{- end }}
  syncPolicy:
    {{- toYaml .Values.externalDns.syncPolicy | nindent 4 }}