apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-cluster
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/codelite7/momentum.git
    path: chart-cluster
    targetRevision: init
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m