// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// Bookmark is the predicate function for bookmark builders.
type Bookmark func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// Thread is the predicate function for thread builders.
type Thread func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// WorkosEventCursor is the predicate function for workoseventcursor builders.
type WorkosEventCursor func(*sql.Selector)
