apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-${name}
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/codelite7/momentum.git
    path: app-chart
    targetRevision: ${targetRevision}
    helm: