apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: api
      custom:
        buildCommand: >
          DOCKER_BUILDKIT=1
          docker build
          --tag $IMAGE
          --build-arg BUILDKIT_INLINE_CACHE=1
          "$BUILD_CONTEXT"
        dependencies:
          dockerfile:
            path: Dockerfile
deploy:
  helm:
    releases:
      - name: api
        namespace: api
        createNamespace: true
        chartPath: ./chart
        version: '>=1.0.0'
        artifactOverrides:
          image: api
        imageStrategy:
          helm: {}
        valuesFiles:
#          - skaffold-values.yaml
           - skaffold-values-local.yaml
        wait: false
portForward:
  # pf for grpc server
  - resourceType: service
    resourceName: api
    namespace: api
    port: 6000
    localPort: 6000
profiles:
  - name: actions
    activation:
      - env: SKAFFOLD_ACTIONS=true
    build:
      artifacts:
        - image: api
          custom:
            buildCommand: >
              docker buildx build
              --tag $IMAGE
              --load
              --cache-from type=gha,mode=max
              --cache-to type=gha,mode=max
              --build-arg BUILDKIT_INLINE_CACHE=1
              "$BUILD_CONTEXT"
            dependencies:
              dockerfile:
                path: Dockerfile
