apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: api
      custom:
        buildCommand: >
          DOCKER_BUILDKIT=1
          docker build
          --tag $IMAGE
          --build-arg BUILDKIT_INLINE_CACHE=1
          "$BUILD_CONTEXT"
        dependencies:
          dockerfile:
            path: Dockerfile
deploy:
  helm:
    hooks:
      before:
        - host:
            command: [ "kubectl", "apply", "--server-side", "-f", "https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/release-1.23/releases/cnpg-1.23.1.yaml" ]
    releases:
      - name: api
        namespace: api
        createNamespace: true
        chartPath: ./chart
        version: '>=1.0.0'
        artifactOverrides:
          image: api
        imageStrategy:
          helm: {}
        valuesFiles:
          - skaffold-values.yaml
          - skaffold-values-local.yaml
        wait: false
profiles:
  - name: actions
    activation:
      - env: SKAFFOLD_ACTIONS=true
    build:
      artifacts:
        - image: api
          custom:
            buildCommand: >
              docker buildx build
              --tag $IMAGE
              --load
              --cache-from type=gha,mode=max
              --cache-to type=gha,mode=max
              --build-arg BUILDKIT_INLINE_CACHE=1
              "$BUILD_CONTEXT"
            dependencies:
              dockerfile:
                path: Dockerfile
