name: Api Langchain Pull Request
run-name: Build api langchain image
on:
  pull_request:
    branches:
      - main
    paths:
      - "api-langchain/**"
jobs:
  image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:api-langchain"
          push: false