name: Deploy
on: # only trigger on prs to main closed
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - terraform
jobs:
  deploy:
    if: github.event.pull_request.merged == true # only deploy on merged PRs
    name: Run Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.CICD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CICD_AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.CICD_ROLE_ARN }}
          role-skip-session-tagging: true
          role-duration-seconds: 1200
      - name: Setup kubectl access
        run: |
          aws eks update-kubeconfig \
            --name manifold-demo \
            --role-arn ${{ cicdRoleArnHere }}
          kubectl config current-context
