name: Api Pull Request
run-name: Build api image
on:
  pull_request:
    branches:
      - main
    paths:
      - "ui/**"
jobs:
  image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM
        uses: bahmutov/npm-install@v1
        with:
          node-version: 20
      - name: NPM Build
        run: |
          npm run build